server:
  port: 8084

spring:
  application:
    name: yujian-task
  profiles:
    active: test

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

xxl:
  job:
    accessToken: default_token
    executor:
      appname: yujian-task
      address:
      ip:
      port: 9999
      logpath: ./logs/xxl-job/jobhandler
      logretentiondays: 30
