server:
  port: 8084

spring:
  application:
    name: yujian-task
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/yujian?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
  redis:
    host: 127.0.0.1
    port: 6379
    database: 3

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/
  instance:
    prefer-ip-address: true

xxl:
  job:
    admin:
      addresses: http://127.0.0.1:8085/xxl-job-admin
    accessToken: default_token
    executor:
      appname: yujian-task
      address:
      ip:
      port: 9999
      logpath: ./logs/xxl-job/jobhandler
      logretentiondays: 30
