server:
  port: 8080

spring:
  application:
    name: yujian-gateway
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    database: 0
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: yujian-admin
          uri: lb://yujian-admin
          predicates:
            - Path=/admin/**
          filters:
            - StripPrefix=1
        - id: yujian-api
          uri: lb://yujian-api
          predicates:
            - Path=/api/**
          filters:
            - StripPrefix=1

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/
  instance:
    prefer-ip-address: true

logging:
  level:
    org.springframework.cloud.gateway: info
