server:
  port: 8086

spring:
  application:
    name: yujian-xxl
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/xxl_job?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/
  instance:
    prefer-ip-address: true

# 官方调度中心地址（独立部署）
xxl:
  job:
    admin:
      addresses: http://127.0.0.1:8085/xxl-job-admin
    accessToken: default_token
