server:
  port: 8086

spring:
  application:
    name: yujian-xxl
  profiles:
    active: test

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

xxl:
  job:
    accessToken: default_token
